apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: my-sample-pod-koseki # Podの名前
  labels:
    app: sample-app
spec:
  containers: # containerの定義
    - name: my-kose-container # container名
      image: nkoseki/hello-node

