---
apiVersion: v1
kind: Service
metadata:
  name: sample-lb-fixip
spec:
  type: LoadBalancer
    #  loadBalancerIP: 192.168.56.52
  externalIPs:
    - 192.168.56.52
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30091
  selector:
    app: sample-app
