---
apiVersion: v1
kind: Service
metadata:
  name: sample-lb2
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 80
      nodePort: 30092
  selector:
    app: sample-app
