---
apiVersion: v1
kind: Service
metadata:
  name: sample-ingress-svc-1
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30081
  selector:
    ingress-app: sample1

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: sample-ingress-apps-1
  labels:
    ingress-app: sample1
spec:
  containers: # containerの定義
    - name: nginx-container 
      image: nginx:1.19
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-ingress-svc-2
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30082
  selector:
    ingress-app: sample2

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: sample-ingress-apps-2
  labels:
    ingress-app: sample2
spec:
  containers: # containerの定義
    - name: nginx-container # container名
      image: nginx:1.19 # containerのimage
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: sample-ingress-default
spec:
  #  type: NodePort
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30083
  selector:
    ingress-app: default

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: sample-ingress-default
  labels:
    ingress-app: default
spec:
  containers: # containerの定義
    - name: nginx-container # container名
      image: nginx:1.19 # containerのimage
      ports:
        - containerPort: 80
