---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-1
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30081
  selector:
    #app: sample-app-1
    ## sample-app-2の選択も可能
    app: sample-app-2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app-1
  template:
    metadata:
      labels:
        app: sample-app-1
    spec:
      containers:
        - name: hello-apache-1
          image: nkoseki/hello-apache
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-2
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30082
  selector:
    app: sample-app-2

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deploy-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-app-2
  template:
    metadata:
      labels:
        app: sample-app-2
    spec:
      containers:
        - name: hello-apache-2
          image: nkoseki/hello-apache
          ports:
            - containerPort: 80

