---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-1
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30081
  selector:
    ingress-app: sample1

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: my-pod-1
  labels:
    ingress-app: sample1
spec:
  containers: # containerの定義
    - name: hello-pod-1
      image: nkoseki/hello-apache
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-svc-2
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30082
  selector:
    ingress-app: sample2

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: my-pod-2
  labels:
    ingress-app: sample2
spec:
  containers: # containerの定義
    - name: hello-pod-2
      image: nkoseki/hello-apache
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-default
spec:
  #  type: NodePort
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8888
      targetPort: 80
      nodePort: 30083
  selector:
    ingress-app: default

---
apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: my-default
  labels:
    ingress-app: default
spec:
  containers: # containerの定義
    - name: hello-default
      image: nkoseki/hello-apache
      ports:
        - containerPort: 80
