apiVersion: v1
kind: Pod # リソースの種類
metadata:
  name: sample-2pod # Podの名前
spec:
  containers: # containerの定義
    - name: nginx-container # container名
      image: nginx:1.13 # containerのimage
    - name: redis-container
      image: redis:3.2

