apiVersion: v1
kind: Pod
metadata:
  name: my-container
spec:
  containers:
    - name: my-work-container
      #      image: gcr.io/distroless/static-debian10
      image: gcriodistroless/base
      command:
        - sleep
        - infinity

