---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
spec:
# spec.strategy.typeのデフォルトは"RollingUpdate"
# "Recreate"だと、既存のすべてのPodは新しいPodが作成される前に削除される
  strategy: 
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: echo-nginx-container
          image: nkoseki/echo-nginx
          ports:
            - containerPort: 80
